version: '3'
   
networks:
  nginx_network:
      external: true

services:
  apidb:
    restart: always
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env

  api:
    restart: always
    build: .
    command: sh deploy.sh
    volumes:
      - .:/code
      - static-data:${STATIC_ROOT}
    env_file: .env
    environment:
      - DEBUG=0
    depends_on:
      - apidb
    networks:
      - nginx_network
      - default

volumes:
  db-data:
  static-data:
