version: '3'
   
networks:
  nginx_network:
      external: true

services:
  apidb:
    restart: always
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  api:
    restart: always
    build: .
    command: sh deploy.sh
    volumes:
      - .:/code
      - static-data:${STATIC_ROOT}
    environment:
      - POSTGRES_HOST=apidb
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - STATIC_ROOT=${STATIC_ROOT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - ADMIN_URL=${ADMIN_URL}
      - DEBUG=0
    depends_on:
      - apidb
    networks:
      - nginx_network
      - default

volumes:
  db-data:
  static-data:
