# Generated by Django 3.2.13 on 2022-06-28 04:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('degree', models.CharField(max_length=255)),
                ('school_en', models.CharField(max_length=255)),
                ('department_en', models.CharField(max_length=255)),
                ('faculty_en', models.CharField(max_length=255)),
                ('awards_en', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None)),
                ('research_en', models.CharField(max_length=255, null=True)),
                ('school_ja', models.CharField(max_length=255)),
                ('department_ja', models.CharField(max_length=255)),
                ('faculty_ja', models.CharField(max_length=255)),
                ('awards_ja', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None)),
                ('research_ja', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('skill_tags', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('company_en', models.CharField(max_length=255)),
                ('position_en', models.CharField(max_length=255)),
                ('status_en', models.CharField(max_length=255)),
                ('descriptions_en', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('examples_en', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('company_ja', models.CharField(max_length=255)),
                ('position_ja', models.CharField(max_length=255)),
                ('status_ja', models.CharField(max_length=255)),
                ('descriptions_ja', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('examples_ja', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill_type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('profiency', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citation', models.CharField(max_length=255)),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.education')),
                ('employment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.employment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.person'),
        ),
        migrations.AddField(
            model_name='education',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.person'),
        ),
    ]
