# Generated by Django 3.2.13 on 2022-06-24 05:56

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillTags',
            new_name='SkillTag',
        ),
        migrations.AlterField(
            model_name='education',
            name='awards_en',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='education',
            name='awards_ja',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='employment',
            name='descriptions_en',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='employment',
            name='descriptions_ja',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='employment',
            name='examples_en',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='employment',
            name='examples_ja',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
