# Generated by Django 3.2.13 on 2022-06-29 06:27

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='certifications',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_ja',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.education'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.employment'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(default='', max_length=63),
        ),
    ]
