# Generated by Django 3.2.13 on 2022-06-23 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='department',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='education',
            name='faculty',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='employment',
            name='company',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='employment',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='employment',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='employment',
            name='position',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='employment',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
