# Generated by Django 3.2.13 on 2022-06-24 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20220624_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
